//For Vehicle Details Page
export const VEHICLE_DETAILS_REQUEST = 'VEHICLE_DETAILS_REQUEST';
export const VEHICLE_DETAILS_SUCCESS = 'VEHICLE_DETAILS_SUCCESS';
export const VEHICLE_DETAILS_FAIL = 'VEHICLE_DETAILS_FAIL';

//For Vehicle create Page
export const VEHICLE_CREATE_REQUEST = 'VEHICLE_CREATE_REQUEST';
export const VEHICLE_CREATE_SUCCESS = 'VEHICLE_CREATE_SUCCESS';
export const VEHICLE_CREATE_FAIL = 'VEHICLE_CREATE_FAIL';

//For User Authentication
export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const NO_LOGGED_IN_USER = 'NO_LOGGED_IN_USER';

//For all categories
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';